spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuce?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 10000
    password: root
    jedis:
      pool:
        max-active:  8 #\u6700\u5927\u8FDE\u63A5\u6570
        max-wait: -1   #\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4(\u8D1F\u6570\u8868\u793A\u6CA1\u9650\u5236)
        max-idle: 8  #\u6700\u5927\u7A7A\u95F2
        min-idle: 0  #\u6700\u5C0F\u7A7A\u95F2



mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.suixingpay.springboot.springboot_test.entity







